### ISSUE TITLE
How to use @RequestModule()

### ISSUE THREAD

**Issue by aryagelato** [jmcdo29/nest-commander#1000]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I was trying to import a service into the command by Dependency Injection but it gives me an error: 

`ERROR [CommandRunnerService] A service tried to call a property of "undefined" in the EcomProductEventsHandleCommand class. Did you use a request scoped provider without the @RequestModule() decorator?`

I have checked your documentation and there is no example of it!

### Minimum reproduction code

```ts
import { Command, CommandRunner, Option } from 'nest-commander';
import { Logger } from '../../common/logger/logger.service';
import { PriceRmqHandlerService } from '../services/price-rmq-handler.service';

interface CommandOptions {
  data?: string;
}

@Command({ name: 'ecom-product-events-handle', description: 'Handling product events from shared bus' })
export class EcomProductEventsHandleCommand extends CommandRunner {
  constructor(
    private readonly logger: Logger,
    private readonly priceRmqHandlerService: PriceRmqHandlerService,
    ) {
    super()
  }

  async run(inputs: string[], options?: CommandOptions): Promise<void> {
    if (options?.data) {
      this.runWithData(inputs, options?.data);
    } else {
      this.runWithNone()
    }
    process.exit(0)
  }

  @Option({
    flags: '-d, --data json',
    description: 'A JSON data parser',
  })
  parseJson(val: string): Object {
    return JSON.parse(val);
  }

  runWithData(param: string[], option: string): void {
    console.log("Running with data...")
  }

  runWithNone(): void {
    console.log("Running...")
  }
}
```

### Expected behavior

because we are importing the main module in `main-cli.ts` like this:

```
async function bootstrap() {
  await CommandFactory.run(AppModule, ['warn', 'error']);
}
```

should do the DI automatically!

### Package

- [X] <code>nest-commander</code>
- [ ] <code>nest-commander-schematics</code>
- [ ] <code>nest-commander-testing</code>

### Package version

3.11.0

### Node.js version

16

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
[There is documentation for it](https://nest-commander.jaymcdoniel.dev/en/features/commander/#request-scoped-commands). And [here's the API docs too](https://nest-commander.jaymcdoniel.dev/en/api/#requestmodule)

**Comment by aryagelato** [comment]
> [There is documentation for it](https://nest-commander.jaymcdoniel.dev/en/features/commander/#request-scoped-commands). And [here's the API docs too](https://nest-commander.jaymcdoniel.dev/en/api/#requestmodule)

I created the module for the command and imported it into the AppModule like this:

```ts
@RequestModule({
    imports: [SharedModule],
    providers: [
        EcomProductEventsHandleCommand,
        Logger,
        PriceRmqHandlerService
    ],
    requestObject: { headers: { Authorization: 'Bearer token' } }
  })
  export class PriceCommandModule {}
```

but still, it's giving me the same error
