### ISSUE TITLE
Not receiving all errors.

### ISSUE THREAD

**Issue by dalirnet** [jmcdo29/nest-commander#1039]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hello,

I understand that my program is generating this error, but no error message is being displayed:

```
Cannot read properties of undefined (reading 'id')
```

I have checked your code and found a [section](https://github.com/jmcdo29/nest-commander/blob/main/packages/nest-commander/src/command-runner.service.ts#L208:L218) that appears to be related:

```js
// command-runner.service.ts#L208:L218
if (err instanceof Error) {
  if (err.message.includes('Cannot read properties of undefined')) {
    const className = /\s+at\s(\w+)\.run/.exec(err.stack ?? '')?.[1];
    this.logger.error(
      `A service tried to call a property of "undefined" in the ${className} class. Did you use a request scoped provider without the @RequestModule() decorator?\n\n${err.message}`,
      err.stack,
      'CommandRunnerService',
    );
    return;
  } else {
    throw err;
  }
} else {
  throw err;
}
```

Do you think this is the correct approach?

### Minimum reproduction code

For example, if we have a command that generates an error with ‍‍`Cannot read properties of undefined` content for any reason.

```js
import { CommandRunner, Command } from "nest-commander";

@Command({
    name: "cmd",
    arguments: "[path]",
    description: "Command",
})
export class MyCommand extends CommandRunner {
 
    constructor() {
        super();
    }

    async run([path = "."]: any): Promise<void> {
        if(true){
            throw new Error("Cannot read properties of undefined (reading 'id')");
        }
    }
}
```

The `serviceErrorHandler` function is never called.

```js
CommandFactory.createWithoutRunning(BootstrapModule, {
    serviceErrorHandler({ message }) {
        console.log("serviceErrorHandler", { message });
    },
})
```

### Expected behavior

I should be able to receive all errors related to my code regardless of the message.

### Package

- [X] <code>nest-commander</code>
- [ ] <code>nest-commander-schematics</code>
- [ ] <code>nest-commander-testing</code>

### Package version

3.11.0

### Node.js version

18.16.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
Yeah, I should expand it to add the original error as well, and probably the stack trace

**Comment by jmcdo29** [comment]
Hmm,. actually, the original error message and the stack should be there. 

Can you provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by dalirnet** [comment]
Minimum reproduction [CodeSandbox](https://codesandbox.io/p/sandbox/mre-nest-commander-ktrc7r).


- Expected `[SUCESS]`

```bash
$ node dist/main.js sample one

# [SUCCESS] The title of this key is: Title of One
```

- Expected `[ERROR]`

```bash
$ node dist/main.js sample two

# [ERROR] My own error handler:
# An error occurred while generating the title
# [ERROR] Service error handler:
# An error occurred while generating the title
```

- Unexpected `[ERROR]`

```bash
$ node dist/main.js sample three

# [ERROR] My own error handler:
# Cannot read properties of undefined (reading 'title')
```

**Comment by jmcdo29** [comment]
Ah! You know what? This is actually all expected, though I can understand why it's a bit strange. `nest-commander` sets the `logger` property to `false` by default, to keep the logs of the created CLI to a minimum. If you do `logger: new ConsoleLogger()`, you'll see all of the expected output

**Comment by dalirnet** [comment]
I understood the point you mentioned, but actually, the issue is not about the log display. It is about not receiving errors through the `serviceErrorHandler` method.
In this example, I attempted to illustrate the problem as a log display issue, but the actual problem remains the same as I mentioned.

**Comment by jmcdo29** [comment]
Ahhh, okay. I keep getting parts of this as we exchange messages and _finally_ think I get what you're saying. I should be calling that custom error handler _as well as_ the liver for the custom message instead of just dropping the error after the log. Okay, that finally all clicked. I'll make a PR and release for it tomorrow. Thanks for your patience as it took me time to get it as straightened out
