### ISSUE TITLE
CLI hangs forever with some modules

### ISSUE THREAD

**Issue by simplenotezy** [jmcdo29/nest-commander#1042]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

If I add:

```ts
BullModule.forRootAsync({
  useFactory: ConfigFactory.bullConfig,
  inject: [ConfigService],
}),
```

To my CliModule it will always run, so if we have cron jobs that uses a cli command it will keep reporting as 'Running'.

If I remove the BullModule the command will exit as usual.

### Minimum reproduction code

https://github.com/simplenotezy/bullmq-and-commander

Run `docker-compose up` to get a redis instance spinning and then you can run `node dist/cli basic` and you'll notice it hangs.

Note: it only happens when after adding the `TestProcessor` to `AppModule`. If you remove the processor, it will work fine.

### Expected behavior

Should not hang

### Package

- [X] <code>nest-commander</code>
- [ ] <code>nest-commander-schematics</code>
- [ ] <code>nest-commander-testing</code>

### Package version

N/A

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

Related to: https://github.com/jmcdo29/nest-commander/discussions/945

**Comment by simplenotezy** [comment]
@jmcdo29 Just clone the reproduction repo but I agree, it seems to end up closing. However, ideally it should exit instantly. Do you have any workaround / solution to have it exit once done?

**Comment by simplenotezy** [comment]
In our production repo I can confirm it hangs forever, it could be related to other modules, but I assume the underlying issue is the same, and if it could be fixed in the redis example, I think it would fix other similar issues as well

**Comment by jmcdo29** [comment]
So, I took your example, and modified it a bit to see if this is directly related to nest-commander, or something else. Changing the `main.ts` to this:
```ts
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import { AppService } from './app.service';

async function bootstrap() {
  // const app = await NestFactory.create(AppModule);
  // await app.listen(3000);
  const app = await NestFactory.createApplicationContext(AppModule);
  console.log(app.get(AppService, { strict: false }).getHello());
  await app.close();
}
bootstrap();
```

And running it **twice** results in the same behavior. It would _seem_ like a queue is being created and not closed immediately. I haven't found the _why_ of that, but I don't believe this is related to nest-commander

**Comment by wodCZ** [comment]
Hi, I'll join this discussion with similar findings to Jay's. 

In my case, a regular `NestFactory.create(AppModule)` exits properly, but the following hangs indefinitely when attempting any kind of exit:

```ts
import { repl } from '@nestjs/core';
import { AppModule } from './app.module';

async function bootstrap() {
  const replServer = await repl(AppModule);
  replServer.setupHistory('.nestjs_repl_history', (err) => {
    if (err) {
      console.error(err);
    }
  });
}

bootstrap().catch(console.error);
```

I've traced it down to bull/redis - the repl stops correctly when I comment out all `registerQueue` calls.

But maybe it's a different issue, on `repl` from `@nestjs/core`?

**Comment by micalevisk** [comment]
@wodCZ maybe? probably due to how the `app` bellow. Not sure why either

![image](https://github.com/jmcdo29/nest-commander/assets/13461315/18dd0858-5825-4c64-a0cd-723eacb07c8a)
https://github.com/nestjs/nest/blob/49cf54e10aed6d30c47bad5975e5141ceeae1b1f/packages/core/repl/repl.ts#L15

**Comment by jmcdo29** [comment]
I'm going to close this as it doesn't seem to be directly related to nest-commander
