### ISSUE TITLE
Prompt for input like Laravel's "Prompts"

### ISSUE THREAD

**Issue by simplenotezy** [jmcdo29/nest-commander#1046]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

When running a command, based on some condition I might want to prompt for more data than what was given to the command. Today I find this either very difficult or not possible for my use-case.

### Describe the solution you'd like

It would be pretty cool if you could prompt for input, like [Laravel Prompts](https://laravel.com/docs/10.x/prompts#text).

```ts
const name = text(
    label: 'What is your name?',
    placeholder: 'E.g. Taylor Otwell',
    default: user.name
);
```

### What is the motivation / use case for changing the behavior?

Improving the developer experience

**Comment by jmcdo29** [comment]
That's what the [`InquirerService`](https://nest-commander.jaymcdoniel.dev/en/features/inquirer/) can be used for, right? Am I missing something here?

**Comment by simplenotezy** [comment]
Yes, and that's what I've been using so far. However, instead of setting questions on the actual class, it would be nice with a way to ask inside the actual run() method, if that makes sense.

**Comment by jmcdo29** [comment]
I'm not really sure I follow

**Comment by jmcdo29** [comment]
@simplenotezy can you elaborate, or can this be closed?

**Comment by simplenotezy** [comment]
Just on the phone but basically I miss some more straightforward way to ask for input from the user without declaring a lot of types and adding decorators to the class, which, if I am not mistaken, is the only way to do it.

Basically, I long for a way to ask for input as simple as:


const name = this.ask.text('What is your name's);

I feel like current approach requires a lot of boilerplate which is not ideal when you're scrapping fast back office commands together. 

Maybe I misunderstood or there is a simpler approach already?
