### ISSUE TITLE
name property in Option decorator has no effect

### ISSUE THREAD

**Issue by rcomesan** [jmcdo29/nest-commander#1070]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

According to the [docs](https://github.com/jmcdo29/nest-commander#commandrunner)
> As for the options, the Record<string, any>, the names of these properties match the name property given to the @Option() decorators, while their value matches the return of the option handler. 

The name property of the Option decorator doesn't seem to work. Maybe I'm missing something, but I'm trying to use it to set the name of the resulting property in the options object that the run method receives.

Thanks.

### Minimum reproduction code

```ts
import { Command, Option, CommandRunner } from 'nest-commander';

interface BasicCommandOptions {
  myRenamedProp: string;
}

@Command({ name: 'basic' })
export class BasicCommand extends CommandRunner {
  @Option({
    name: 'myRenamedProp',
    flags: '-p, --prop [boolean]',
  })
  parseProp(val: string): boolean {
    return JSON.parse(val);
  }

  async run(passedParam: string[], options: BasicCommandOptions): Promise<void> {
    console.log(options); // { prop: true }
  }
}
```

### Expected behavior

I expect  myRenamedProp to be true when using the -p or --prop option.
```
Expected: { myRenamedProp: true }
Actual: { prop: true }
```

### Package

- [X] <code>nest-commander</code>
- [ ] <code>nest-commander-schematics</code>
- [ ] <code>nest-commander-testing</code>

### Package version

3.12.0

### Node.js version

18.18.2

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by jmcdo29** [comment]
Interesting. Can you provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by jmcdo29** [comment]
All right, I see the reproduction does exactly what you mentioned (thank you for that), and I think there was a change in commander that removed the use of `name` in the option. I can work on setting up a mapper for this, to keep the functionality, but it might take a bit to make sure it works exactly as expected.

**Comment by jmcdo29** [comment]
Fixed in 3.12.1. Thanks for reporting

**Comment by rcomesan** [comment]
Hey @jmcdo29, thanks for your super fast help but I'm afraid there's still some weird behavior going on. Dashed properties seem to be included in the options object with an undefined key.

I've upgraded nest-commander to the latest version 3.12.1, and I've added 2 new options to show this behavior in my [repository](https://github.com/rcomesan/commander-option-name-repro).

You can run it with 
`npm run cli -- basic -p -r -d`

Expected output should be:
`{ myRenamedProp: true, myRenamedDashedProp: true, dashedProp: true }`

Actual output now is:
`{ myRenamedProp: true, undefined: true }`

**Comment by jmcdo29** [comment]
Oh interesting. Let me take a look. I didn't have a test case for a Dasher property

**Comment by jmcdo29** [comment]
All right, swapped from `option.name()` to `option.attributeName()` which is what comamnder uses under the hood after camelCasing the options from their dashed-state. 3.12.2 should fix that once published. Thanks for the quick follow up
