### ISSUE TITLE
TypeError: Cannot read properties of undefined

### ISSUE THREAD

**Issue by sam-artuso** [jmcdo29/nest-commander#1084]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I'm trying to inject a service into a command. The project builds, but when I invoke the command, I get the error

```
TypeError: Cannot read properties of undefined
```

I'm quite sure my problem has got to do with the fact that the injected service is request-scoped, but I have no idea how to fix my code. Can anybody help?

To run my command:
```
pnpm run cli test
```

### Minimum reproduction code

https://gitlab.com/kYuZz/minimum-repro

### Expected behavior

No error.

### Package

- [X] <code>nest-commander</code>
- [ ] <code>nest-commander-schematics</code>
- [ ] <code>nest-commander-testing</code>

### Package version

3.12.5

### Node.js version

20.5.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
So there's two things here: 

1) the module that instantiates the `REQUEST` scoped property is the one that needs `@RequestModule()`

2) the `scope: Scope.REQUEST` **cannot** be there for the `RequestModule` to properly setup a mock request to make the `REQUEST` provider singleton scoped for the sake of the command.

```diff
diff --git a/src/category/module.ts b/src/category/module.ts
index 3e86c7e..3b57a92 100644
--- a/src/category/module.ts
+++ b/src/category/module.ts
@@ -1,6 +1,6 @@
-import { Module, Scope } from '@nestjs/common'
 import { ConfigModule, ConfigService } from '@nestjs/config'
 import { REQUEST } from '@nestjs/core'
+import { RequestModule } from 'nest-commander'
 
 import { HttpClientService } from '../http-client'
 
@@ -15,18 +15,18 @@ const httpClientServiceFactory = (configService: ConfigService, request: Request
   return new HttpClientService(baseUrl, requestTimeout, request)
 }
 
-@Module({
+@RequestModule({
   imports: [ConfigModule.forFeature(categoryServiceConfig)],
   providers: [
     {
       provide: 'api',
       useFactory: httpClientServiceFactory,
       inject: [ConfigService, REQUEST],
-      scope: Scope.REQUEST,
     },
     CategoryService,
   ],
   exports: [CategoryService],
+  requestObject: { headers: { Authorization: 'Bearer TOKEN' } },
 })
 class CategoryModule {}
 ```

With this diff, things work as expected

**Comment by sam-artuso** [comment]
I'm confused. If I do this, my app doesn't work in non-CLI environment because `api` is not request-scoped anymore?
