### ISSUE TITLE
Prevent processing of queues when app is run via nest-commander

### ISSUE THREAD

**Issue by julianpensionjar** [jmcdo29/nest-commander#1180]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Quick explanation of the situation:
- We have a RESTful Backend API Service built on NestJS
- Within the backend, there is also a fair amount of asynchronous processing required, and for that we use Redis for queueing, and Bull (as per https://docs.nestjs.com/techniques/queues) to post tasks to queues with `@Processor()` decorator on various methods throughout the app modules to consume tasks
- We also have scheduled tasks, and for this we use nest-commander with a command line entry point that can be called from our cloud provider schedule system. Effectively this spins up an instance of the app, allowing nest-commander to "route" to the relevant command handler (using `@Command()` decorators) and run the relevant module service function

A simplifier version of this entry point is:

```
async function bootstrap() {
  await CommandFactory.run(MainModule, ['warn', 'error'])
}

bootstrap()
  .then(async () => {
    process.exit(0)
  })
  .catch(() => {
    process.exit(1)
  })
```
Note that `CommandFactory` run is using `MainModule` which sets up the entire app (the same as for regular "web" instances serving the main API endpoints). A lot of config happens in `MainModule` and we punch in at the same place for commands, because the specific command being run could "belong" to any of the modules in the app.

The issue is that I _think_ when an instance of the app is spun up by the scheduler (as per above), it is sometimes **also** collecting the occasional task from the queues via the Bull `@Processor()` decorators. I've certainly found log entries that suggest this is the case. I'm not currently clear how this fact interacts with the simple bootstrap handling above which exits the process when it is complete. I'm concerned that I might be "losing" tasks, or perhaps terminating them part way through processing.

So, in short, what I'm wondering is how an instance of the application can "understand" whether or not it is running via nest-commander. If I can either pass this knowledge into `MainModule`, or simply "pick it up" during lower-level processing somehow, then I can suppress the queue processing for the app instances running via the scheduler and nest-commander.

I appreciate this question is only partly about nest-commander, but wondering if anyone has run into anything similar and has a solution?

### Describe the solution you'd like

In short, I need an approach for ensuring that app instances created via nest-commander `CommandFactory` "understand" that they are running in this mode so that unwanted functionality such as queue processing can be disabled.

### What is the motivation / use case for changing the behavior?

Complex app using all 3 of these techniques:
- Serving web clients
- Running scheduled tasks
- Processing asynchronous tasks using queues

**Comment by jmcdo29** [comment]
This is less of something that `nest-commander` would be able to do, without a very complex underlying search to remove the `BullModule` (or similar). What would be better would be to treat your CLI as a secondary application, and add only the necessary module. [That's what I do in my Unteris project](https://github.com/jmcdo29/unteris) where the CLI is a migration runner and database seeder, while there also exists two other servers (one as a microservice, the other as a main HTTP server). This allows full control for what the CLI application needs while reducing the startup complexity

**Comment by julianpensionjar** [comment]
Ok thanks - I can understand the sentiment of your response - it just means that I have to segregate queue-processing functionality completely from everything else (i.e. at module level) to avoid it being included in the secondary application. A level of additional abstraction I was hoping to avoid, but there may be some other benefits to doing so anyway.
