### ISSUE TITLE
Could not find a declaration file for module 'inquirer'.

### ISSUE THREAD

**Issue by uiii** [jmcdo29/nest-commander#179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

```
node_modules/nest-commander/src/inquirer.service.d.ts:2:42 - error TS7016: Could not find a declaration file for module 'inquirer'. '/usr/src/app/node_modules/nest-commander/node_modules/inquirer/lib/inquirer.js' implicitly has an 'any' type.    
Try `npm i --save-dev @types/inquirer` if it exists or add a new declaration (.d.ts) file containing `declare module 'inquirer';`
```

### Minimum reproduction code

1. install nest-commander
2. create a command with it
3. run app

### Expected behavior

No error is shown.

### Package

- [X] <code>nest-commander</code>
- [ ] <code>nest-commander-schematics</code>
- [ ] <code>nest-commander-testing</code>

### Package version

2.3.4

### Node.js version

17.2.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by smolinari** [comment]
@uiii - Did you try and install the types, as suggested?

Scott

**Comment by uiii** [comment]
Yes and it helped. But the package should provide the typing.

**Comment by smolinari** [comment]
@uiii - It does. Not sure why your installation was missing it. 

Scott

**Comment by uiii** [comment]
the problem is in built typings in file `inquirer.service.d.ts`:
```ts
import { DiscoveryService } from '@golevelup/nestjs-discovery';
import { Inquirer as InquirerType } from 'inquirer'; // <-- THERE
export declare class InquirerService {
    private readonly inquirer;
    private readonly discoveryService;
    constructor(inquirer: InquirerType, discoveryService: DiscoveryService);
    private readonly inquirerKeyToMetadataKeyMap;
    ask: <T>(questionSetName: string, options: Partial<T> | undefined) => Promise<T>;
    prompt<T>(questionSetName: string, options: Partial<T> | undefined): Promise<T>;
    private findQuestionSet;
    private mapMetaQuestionToQuestion;
    private parseRawQuestionMetadata;
}
```

**Comment by jmcdo29** [comment]
Would you mind providing a repository that shows this? I tried using `nest new` (albeit with `pnpm`)and added the `InquirerService` and couldn't get the error during `nest build`. Even with setting `skipLibCheck: false` and `incremental: false` I couldn't trigger the same error. I'll try with `npm` as well just to check, but if you can provide a repo it'll speed this up.

**Comment by uiii** [comment]
Sorry, it would be too complicated. I use `yarn` not npm and running the code in a docker container. And it was added in an older nestjs project. I can provide you concrete files if you want.

**Comment by jmcdo29** [comment]
Even `yarn build` is providing a success for me. I can't reproduce the error you have above, at least outside of a docker container. Should I be needing to do anything else other than install and build to see this error? Types shouldn't be checked at runtime, so I believe `pnpm build`/`yarn build`/`npm run build` should reproduce the error, right?

**Comment by uiii** [comment]
hmm 🤔 yes the true is the types are checked even the package is in `node_modules` which I think too it shouldn't. Can you provide me the `nest-commander` folder from `node_modules` I can compare with mine.

**Comment by uiii** [comment]
and also the `tsconfig.json`

**Comment by jmcdo29** [comment]
<details>
  <summary>Here's the output. This is why a minimum reproduction is usually asked for</summary>

### tsconfig.json

```json
	{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "es2017",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": false,
    "skipLibCheck": false,
    "strictNullChecks": false,
    "noImplicitAny": false,
    "strictBindCallApply": false,
    "forceConsistentCasingInFileNames": false,
    "noFallthroughCasesInSwitch": false
  }
}
```

### Tree of `node_modules/nest-commander`

```ym
node_modules/nest-commander
├── CHANGELOG.md
├── LICENSE
├── node_modules
│  └── commander
│     ├── esm.mjs
│     ├── index.js
│     ├── lib
│     ├── LICENSE
│     ├── package-support.json
│     ├── package.json
│     ├── Readme.md
│     └── typings
├── package.json
├── README.md
└── src
   ├── command-factory.interface.d.ts
   ├── command-factory.interface.js
   ├── command-factory.interface.js.map
   ├── command-root.module.d.ts
   ├── command-root.module.js
   ├── command-root.module.js.map
   ├── command-runner.interface.d.ts
   ├── command-runner.interface.js
   ├── command-runner.interface.js.map
   ├── command-runner.module.d.ts
   ├── command-runner.module.js
   ├── command-runner.module.js.map
   ├── command-runner.service.d.ts
   ├── command-runner.service.js
   ├── command-runner.service.js.map
   ├── command.decorators.d.ts
   ├── command.decorators.js
   ├── command.decorators.js.map
   ├── command.factory.d.ts
   ├── command.factory.js
   ├── command.factory.js.map
   ├── constants.d.ts
   ├── constants.js
   ├── constants.js.map
   ├── index.d.ts
   ├── index.js
   ├── index.js.map
   ├── inquirer.service.d.ts
   ├── inquirer.service.js
   └── inquirer.service.js.map
```

</details>

**Comment by uiii** [comment]
hmm, mine `tsconfig.json` is this:
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "es2017",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,
    "esModuleInterop": true,
    "strict": true,
    "noUncheckedIndexedAccess": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": false
  },
  "exclude": [
    "node_modules",
    "dist"
  ]
}
```

**Comment by uiii** [comment]
if I add `"skipLibCheck": true` it work fine, but I think it should work without it, doen't it?

**Comment by jmcdo29** [comment]
Looks like it's the use of `strict` mode (which I encourage) that does this. Nest has `skipLibCheck` turned on by default, which is the other reason a `nest new` project was working just fine. 

I think the best solution here is to make `@types/inquirer` a peerDependency and update the documentation to mention the install and that it is required if Typescript is in `strict` mode and `skipLibCheck` is `false`. Thanks for bringing this up.

**Comment by uiii** [comment]
Ah yes I see, strict mode enables `noImplicitAny: true` and the import without types is typed as `any`

**Comment by jmcdo29** [comment]
Feel free to make a PR to address this. Otherwise I'll try to get to it later this week

**Comment by uiii** [comment]
maybe you could also solve it to set the type of `inquirer` as `any` explicitely in your package, but not sure about this

**Comment by uiii** [comment]
> Feel free to make a PR to address this. Otherwise I'll try to get to it later this week

I can wait I will install `@types/inquirer`

**Comment by uiii** [comment]
thank you
