### ISSUE TITLE
[docs] Add 'last update' date on each page

### ISSUE THREAD

**Issue by micalevisk** [jmcdo29/nest-commander#187]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Looking at https://jmcdo29.github.io/nest-commander/docs, the only way to figure out if something has changed since the last time we read any page is by reading it entirely.

### Describe the solution you'd like

I've never used Docusaurus before but I guess we just need to add the `plugin-content-docs` on `docusaurus.config.js` with the option [`showLastUpdateTime`](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-docs#showLastUpdateTime)

![image](https://user-images.githubusercontent.com/13461315/147396471-0c7a7625-1b79-4cff-ac21-46c893da102c.png)

(taken from https://docusaurus.io/docs that [uses the option `showLastUpdateAuthor` as well](https://github.com/facebook/docusaurus/blob/e1bff072feac06cd0c40353e8a50d108394be02f/website/docusaurus.config.js#L141-L142))

### What is the motivation / use case for changing the behavior?

Let users know easily (sort of) if they're reading a new version of some page

**Comment by micalevisk** [comment]
btw I miss this feat on https://docs.nestjs.com :/ but looks like adding it in there won't be that easy

**Comment by jmcdo29** [comment]
I'd love to see this added. It should be a pretty simple addition, right?

**Comment by micalevisk** [comment]
I believe so
