### ISSUE TITLE
Wrong injections fails silently

### ISSUE THREAD

**Issue by micalevisk** [jmcdo29/nest-commander#188]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I'm not really sure if this is just a limitation or a bug, tbh.

When we try to inject a provider that was not registered, the CLI process exits with 1 but no errors are displayed.

### Minimum reproduction code

1. add `constructor(@Inject('bar') private readonly bar: any) {}` to your command class
2. run the CLI
3. the process will exit with `1` code but silently

### Expected behavior

Behaves the same as NestJS behaves when the injection fails, ie., display [_cannot resolve dependency_ error](https://docs.nestjs.com/faq/common-errors#cannot-resolve-dependency-error) message.

### Package

- [X] <code>nest-commander</code>
- [ ] <code>nest-commander-schematics</code>
- [ ] <code>nest-commander-testing</code>

### Package version

2.3.4 _(the latest)_

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
This is due to the default `logger: false`. Just to keep the command logs clean when commands are published.

**Comment by micalevisk** [comment]
oh, right

![image](https://user-images.githubusercontent.com/13461315/147397945-12b00641-7f3b-47da-be1e-f1ce74ce03d8.png)

makes sense. Ty!
