### ISSUE TITLE
Adding 'choices' within the option decorator

### ISSUE THREAD

**Issue by jmcdo29** [jmcdo29/nest-commander#327]
### Discussed in https://github.com/jmcdo29/nest-commander/discussions/326

<div type='discussions-op-text'>

<sup>Originally posted by **BenSawary** March 18, 2022</sup>
I'd like to define a valid list of a commands option argument. Since commander 7, (https://github.com/tj/commander.js/issues/518) it is possible to create an option with choices. Is it possible to add this functionality also in the nest-commander option decorator?

@Option({
    flags: '--option [option]',
    choices: ['a', 'b', 'c'],
    defaultValue: 'a'
  })
setOption(option: string) {}</div>

**Comment by BenSawary** [comment]
Hi Jay, an additional configuration could be dynamic choices. Decorators are used in a static manner, if we want to add the choices dynamically, then we could provide this over a function. 

export interface OptionMetadata {
    flags: string;
    description?: string;
    choices?: string[] | () => string[];
    defaultValue?: string | boolean;
    required?: boolean;
}

An alternative of that approach could be a second Decorator. We could use it in the same way as in the Inquirer API:

@Option({
   flags: '--option [option]',
   defaultValue: 'a'
})
setOption(option: string) {}

@OptionChoicesFor({name: option})
getOptionChoices(): string[] {}

**Comment by jmcdo29** [comment]
I really like the `@OptionFor()` approach, so I'll probably go with that over using a function inside the decorator, thanks for calling this out as an option.

**Comment by jmcdo29** [comment]
Added support in 2.5.0

**Comment by DanielMaranhao** [comment]
Hello, does the `choices` inside `@Option()` works for actually enforcing these values, or simply as documentation? For some reason I'm trying to use this option but the values are not being enforced. Thanks in advance.
