### ISSUE TITLE
Adding Sub commands don't seem to work

### ISSUE THREAD

**Issue by gr0wth-b0t** [jmcdo29/nest-commander#354]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Defining sub commands is not working. only parent command is being called

### Minimum reproduction code

Going with the example provided in the docs, tried to create a commander cli application using this repo, with the following code:

```typescript
@SubCommand({ name: 'foo', arguments: '[phooey]' })
export class FooCommand implements CommandRunner {
  async run(
    inputs: string[],
    options: Record<string, string>
  ): Promise<void> {
    console.log('inside FooCommand class!');
  }
}

@Command({
  name: 'run',
  arguments: '<task>',
  subCommands: [FooCommand]
})
export class RunCommand implements CommandRunner {
  async run(
    inputs: string[],
    options: Record<string, string>
  ): Promise<void> {
    console.log('inside RunCommand class!');
  }
}
```

The only difference is that I had to implement the `run` command in the `RunCommand` class because it's required by the `CommandRunner` interface.

Right now, when I run the application with either:
 - `npx ts-node ./src/bootstrap.ts run`
 - `npx ts-node ./src/bootstrap.ts run foo`
 - `npx ts-node ./src/bootstrap.ts run foo test`
I get only the `inside RunCommand class!` printed.

### Expected behavior

Extected to print `inside FooCommand class!` to the console since the sub command run function should be called.

### Package

- [X] <code>nest-commander</code>
- [ ] <code>nest-commander-schematics</code>
- [ ] <code>nest-commander-testing</code>

### Package version

2.4.0

### Node.js version

14.18.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by simplenotezy** [comment]
Not sure why @gr0wth-b0t closed this, but I am facing a similar issue
