### ISSUE TITLE
Add option to set up command alias

### ISSUE THREAD

**Issue by Thatkookooguy** [jmcdo29/nest-commander#360]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Commander supports command aliases out of the box. Currently, we need to get the commander instance to add an alias to a command

### Describe the solution you'd like

```
@SubCommand({
  name: 'migration',
  alias: 'mi',
  description: 'generate a db migration'
})
export class MigrationGeneratorCommand implements CommandRunner {
...
```

### What is the motivation / use case for changing the behavior?

command aliases is pretty common use case for generators

**Comment by micalevisk** [comment]
with Commander, can we have multiple aliases?

**Comment by jmcdo29** [comment]
From the source code, it looks like an array of aliases is possible, and it's only for sub-commands, is that correct?

**Comment by micalevisk** [comment]
so what about this interface instead:

```ts
@SubCommand({
  // name: 'migration', // Still allowed
  name: ['migration', 'mi', 'm'],
  description: 'generate a db migration'
})
```

**Comment by jmcdo29** [comment]
I think I'd rather we have `name` be a string as the main name of the command, and allow for an `aliases` where we do `aliases.forEach(alias => command.alias(alias))`. I think it'll fair better with the `--help` command as well

**Comment by jmcdo29** [comment]
Added support in 2.5.0
