### ISSUE TITLE
CommandTestFactory - Passing options (flags) returns wrong values

### ISSUE THREAD

**Issue by gCardinal** [jmcdo29/nest-commander#38]
It might be a lack of documentation, but I can't understand how `CommandTestFactory` would want me to pass option flags to my command. Imagine the following command class (simplified for ease of reading):

```typescript
@Command({
  name: 'generate',
  description: 'Generate a new project',
})
export class GenerateCommand {
  public async run(input: string[], options: GenerateCommandOptions): Promise<void> {
    const { name, description, ...requirements } = await this.promptForMissingOptions('generate', options);

    await this.generate(new ProjectSchema(name, description, requirements));
  }

  @Option({ flags: '-o, --open-api' })
  public openApi(openApi: string): boolean {
    return openApi === 'true';
  }

  @Option({  flags: '-r, --rabbit' })
  public rabbitMqClient(rabbitMqClient: string): boolean {
    return rabbitMqClient === 'true';
  }

  @Option({ flags: '-g, --originator' })
  public originator(originator: string): boolean {
    return originator === 'true';
  }
}

```

If I test this command with the following:

```typescript
it(`creates a schema and generates the project`, async () => {
  await CommandTestFactory.run(commandInstance, [
    'generate',
    '--name',
    'Foo',
    '--description',
    'Desc',
    '--open-api',
    'false',
    '--rabbit',
    'true',
    '--originator',
    'false',
  ]);
});
```

It does not work, my command's `.run()` method will receive `['false', 'false', 'false']` as its `input` parameter, like they are regular arguments, not options and the `rabbit` option will still be `false` even though I would assume it should be `true` with the above.

I'm really not sure what's going on here, any help would be greatly appreciated :)

**Comment by jmcdo29** [comment]
Strange. Do you have a minimum reproduction?

**Comment by gCardinal** [comment]
Yep: https://github.com/gCardinal/nest-commander-repro. Hopefully it helps.

You can run the test to see the issue, but to better understand what I mean, you'll want to [step debug on this line](https://github.com/gCardinal/nest-commander-repro/blob/master/src/commands/generate/nestjs.command.ts#L35) to see that `options` and `requirements` will both list the flags as being false.

I'm sure it's something I have not understood in how `CommandTestFactory` should be used. If that's the case, I wouldn't mind getting a PR going to add the missing information to the documentation.

**Comment by jmcdo29** [comment]
In `@Option()`s you're missing the property name to save the decorator to. It should be `flag: '-o,--open-api [openApi]'`. Otherwise it comes in as undefined

**Comment by gCardinal** [comment]
I see, so it is indeed a silly mistake on my part.

Where should I have seen this documented? I dug a bit this morning and if I'm understanding correctly, `nest-commander` is, to put it simply, just a wrapper around `commander` and `inquirer`. That being the case, when declaring an `@Option()`, one should look at `commander`'s documentation to determine what is possible?

**Comment by jmcdo29** [comment]
I don't see this explicitly stated in commander's docs, but I can see that any option that is hyphenated, that does not have `no-` (i.e. `--no-rabbit`) does have either `[]` or `<>` wrapping around the option name. I'll take a look at the PR and see what you've got in addition. Thanks for opening one up!

**Comment by gCardinal** [comment]
For anyone stumbling upon this question and struggling with boolean flags like I was, here's a small example of what works (including negative flags). No need for `[]` or `<>`:

```typescript
@QuestionSet({ name: 'nestjs_questions' })
export class NestjsQuestions extends GenerateQuestions {
  public static NAME = 'nestjs_questions';

  @Question({
    name: 'rabbitMqClient',
    message: 'Do you require a RabbitMQ client to be configured?',
    type: 'confirm',
  })
  public rabbitMqClient(rabbitMqClient: string): boolean {
    return rabbitMqClient === 'true';
  }
}

@Command({
  name: 'nestjs',
  description: 'Generate a new NestJS project',
})
export class GenerateNestjsCommand implements CommandRunner {
  public constructor(
    private readonly inquirer: InquirerService,
  ) {}

  public async run(
    input: string[],
    options: GenerateNestjsCommandOptions,
  ): Promise<void> {
    const responses =
      await this.inquirer.ask<GenerateNestjsCommandOptions>(
        NestjsQuestions.NAME,
        options,
      );
    
    // Stuff
  }

  @Option({
    flags: '-r, --rabbit-mq-client',
    description: "setup Station Casinos' RabbitMQ client module",
  })
  public rabbitMqClient(): boolean {
    return true;
  }

  @Option({
    flags: '--no-rabbit-mq-client',
    description: "do not configure Station Casinos' RabbitMQ client module",
  })
  public noRabbitMqClient(): boolean {
    return false;
  }
}

```

With this, your command will prompt the user if no flag is given, but will not prompt if `-r`, `--rabbit-mq-client` or `--no-rabbit-mq-client` is given, with the first two flags setting `rabbitMqClient` to `true` and the last one to `false`.

Hope it can help someone :)
