### ISSUE TITLE
Two dots system like node scripts into the package.json

### ISSUE THREAD

**Issue by rakicluca** [jmcdo29/nest-commander#484]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

At the moment we can "only" use flags or subcommand. It would be nice to be able to use the dots ( **:** ) like in the scripts section of the package.json

### Describe the solution you'd like

I would like to be able to create commands like the node scripts (ex start:dev) instead of using the subcommand (ex start dev). Is this option already available?

### What is the motivation / use case for changing the behavior?

There is no a concrete motivation, is just a personal preference and, imho, is always good to be able to make a choice instead of being "obligated" to use a determined "workflow".

**Comment by jmcdo29** [comment]
Would `start:dev` here be a single command or would `start` be a command with `:dev` being a sub command of it? Or an option/flag of some sort? If it's just that `start:dev` itself is a single command I'm pretty sure you can just call the command that, but if it's  a subcommand then I don't believe commander has that capabilitiy

**Comment by smolinari** [comment]
I have to ask, for a "why" too? Having to type a colon is one more key that needs two more keystrokes (on my German keyboard) for no apparent reason. There is also no standard within the CLI commands of any package I know of where a colon is used, so I can't imagine this "workflow" would be wished for by anyone. 

Scott

**Comment by rakicluca** [comment]
@jmcdo29 thanks for the reply. Yeah, I think that two commands with that name would be fine for me :)

**Comment by rakicluca** [comment]
@smolinari as I wrote was a pretty personal preference, not any particular reason.
