### ISSUE TITLE
Option parse method not called when using choices 

### ISSUE THREAD

**Issue by b4cedev** [jmcdo29/nest-commander#522]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

If you supply `choices` for an `@Option()` the annotated method is not called by commander.

If you have a look at the reproduction replit you'll see that the `parseOption` method contains a `console.log()` statement. If you run it you'll see that it does not log as expected.

### Minimum reproduction code

https://replit.com/@b4cedev/nest-commander-choices-parser#src/basic-command.command.ts

### Expected behavior

The `console.log()` statement in `parseOption` method should be executed and produce ouput.

The reason seems to be the order of first calling `.argParser()` then `.choices()` in `command-runner.service.ts`. If you call them in reverse order it works as expected. At least for this case...

### Package

- [X] <code>nest-commander</code>
- [ ] <code>nest-commander-schematics</code>
- [ ] <code>nest-commander-testing</code>

### Package version

2.5.0

### Node.js version

14:17.1

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by jmcdo29** [comment]
Huh, interesting. I wonder if I'll need to add a case in here for if `choices` is set directly instead of using `@OptionChoicesFor()`. I'll look into this over the weekend, thanks for the repo
