### ISSUE TITLE
@Option defaultValue not parsed

### ISSUE THREAD

**Issue by andreyan-andreev** [jmcdo29/nest-commander#541]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

`
@Option({
        flags: '-l, --idx-max-length [number]',
        description: 'Max length of idx',
        defaultValue: '30'
    })
    parseIdxLength(val: string): number {
        return Number(val);
    }
`

When left as default, meaning not supplied on the command line, the result is like this:
`
  idxMaxLength: '30' 
`

I tried to go around this with setting number as default value but then the ide is crying because it can accept only string or boolean.

### Minimum reproduction code

* See above

### Expected behavior

* See above

### Package

- [X] <code>nest-commander</code>
- [ ] <code>nest-commander-schematics</code>
- [ ] <code>nest-commander-testing</code>

### Package version

2.4.0

### Node.js version

14

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

thank you.

**Comment by jmcdo29** [comment]
Could you add an example of the command you're running? If I recall correctly, the `defaultOption` is for if you pass the option flag, but don't provide a value explicitly. Either way a [minimum reproduction](https://minimum-reproduction.wtf) would be helpful to have if this is a bug

**Comment by andreyan-andreev** [comment]
Hi,
The issue I am facing is with the `defaultValue` for the `@Option` decorator.
When the option, in the example above it would be --idx-max-length is not supplied on the command line the defaultValue is used, however it is not processed by the decorated function, in my case `parseIdxLength(val: string): number { return Number(val)` this results in `options. idxMaxLength` being a string instead of number.

Hope this makes any sense, if not, please close the issue.

Thank you.

**Comment by jmcdo29** [comment]
Ah, I understand now. I think I should end up modifying the interface so it can be a number as well. Or find some way to force commander to use the parsing function with the default value. The former sounds easier to fix though.

**Comment by michaelrosett** [comment]
How come the default value is not passed to the parse method?

Here's the scenario I'm up against with the following setup...

```
enum Environment {
  LOCAL,
  DEV,
  STAGING,
  PROD,
}

interface ValidateCommandOptions {
  environments: Environment[];
}

@Option({
  flags: '--environments [comma-separated environments]',
  description: 'A list of environments (e.g. local,dev,staging)',
  required: true,
})
environments(val: string): Environment[] {
  return val
    .toUpperCase()
    .split(',')
    .map((environment) => Environment[environment]);
}
```

In this case ValidateCommandOptions ends up CORRECTLY as:
```
{
  "environments": [1, 2, 3]
}
```

If I change the @Option and make `required: false` and add `defaultValue=local,dev,staging,prod` the method to parse the `environments` is never called and ValidateCommandOptions ends up INCORRECT as:
```
{
  "environments": "local,dev,staging,prod"
}
```

I'm trying to understand why defaultValue wouldn't go through the parser method just like a value passed on the command line?
