### ISSUE TITLE
@Option inoperative

### ISSUE THREAD

**Issue by MrYbo** [jmcdo29/nest-commander#559]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

@option was configured, but nothing happened

### Minimum reproduction code

```ts
import { Command, CommandRunner, Option } from 'nest-commander';

@Command({
  name: 'say-hello',
  options: {
    isDefault: true,
  },
})
export class TaskRunner extends CommandRunner {
  constructor() {
    super();
  }

  async run(
    passedParam: string[],
    options?: Record<string, number>,
  ): Promise<void> {
    console.log('----1->', passedParam, options);
  }

  @Option({
    flags: '-id, --number [number]',
    description: 'A integer',
  })
  parseNumber(val: string): number {
    return Number(val);
  }
}


```

### Expected behavior

Execute the command:

```
 npm run start:task say-hello --number 12345  
```

The console can be printed out：

```
----1-> [ '12345' ] {number: 12345}
```

but The actual printed result is:

```
----1-> [ '12345' ] {}
```

### Package

- [X] <code>nest-commander</code>
- [ ] <code>nest-commander-schematics</code>
- [ ] <code>nest-commander-testing</code>

### Package version

3.0.0

### Node.js version

16.16.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
With `--` flags you should use the form `--number=12345`. Let me know if that changes the output for you. If not, please provide a [minimum reproduction repository](https://minimum-reproduction.wtf)

**Comment by MrYbo** [comment]
sorry, It's my fault. I added the command to package.json:  `"start:task": "Nest build && node dist/tasks/main"`, and then when I run `nest run start:task -n`, I can't pass the `-n` parameter to the `node dist/tasks/main` parameter

**Comment by jmcdo29** [comment]
I believe this is specific to each package manager. With `npm` I believe you need to use a `--` to separate options for npm and options for the script, so `npm run start:task -- -n`. With `pnpm` you just add everything directly `pnpm start:task -n` and I think `yarn` is the same way

**Comment by MrYbo** [comment]
yes, `npm run start:task -- -n` ,This approach is very effective, Thank you very match.👍👍👍
