### ISSUE TITLE
implement `CommandRunner` or extend `CommandRunner`

### ISSUE THREAD

**Issue by genu** [jmcdo29/nest-commander#568]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The schematic currently implements the `CommandRunner` which produces type errors in generated command.

### Minimum reproduction code

```bash
nest g -c nest-commander-schematics command
```

### Expected behavior

Manually changing t command from `implements CommandRunner` to `extends CommandRunner` fixes the issue.

### Package

- [ ] <code>nest-commander</code>
- [X] <code>nest-commander-schematics</code>
- [ ] <code>nest-commander-testing</code>

### Package version

3.0.0

### Node.js version

18.4.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

Docs extend `CommandRunner` but generated command from schematics seem to implement it.

**Comment by jmcdo29** [comment]
Oh! Looks like part of the schematic that I need to fix. Thanks for bringing this to my attention. I'll try to have it fixed later this week

**Comment by jmcdo29** [comment]
Should be available with nest-commander-schematics@3.0.0
