### ISSUE TITLE
Clarify documentation

### ISSUE THREAD

**Issue by GoodGuyMarco** [jmcdo29/nest-commander#57]
Hey folks,

I'm trying to use this package but having troubles understanding how to execute my commands. I have created a `cli.ts` with the bootstrap function as pointed out here: https://github.com/jmcdo29/nest-commander#putting-it-all-together

In my `package.json` I have created a script with following content: `node build/cli`. When I try to run it it is giving me following error: `Cannot find module '@nestjs/common'` although I have it installed in my dependencies.

What am I doing wrong?

**Comment by jmcdo29** [comment]
That's interesting. Can you [provide a minimum reproduction](http://minimum-reproduction.wtf)

**Comment by jmcdo29** [comment]
If you can provide some more information, I'll be happy to look into what could be happening. I;m going to close this out for now though. Feel free to reopen with extra info and/or a reproduction.
