### ISSUE TITLE
Installing nest-commander-testing fails with dependency resolution error

### ISSUE THREAD

**Issue by 123FLO321** [jmcdo29/nest-commander#571]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

However when installing nest-commander-testing it fails on npm 8 with a dependency resolution error:
```
$ npm i nest-commander @nestjs/common @nestjs/core nest-commander-testing
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: undefined@undefined
npm ERR! Found: nest-commander@3.0.0
npm ERR! node_modules/nest-commander
npm ERR!   nest-commander@"^3.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer nest-commander@"^2.5.0" from nest-commander-testing@3.0.0
npm ERR! node_modules/nest-commander-testing
npm ERR!   dev nest-commander-testing@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

### Minimum reproduction code

1. Install npm version `8.16.0`
2. `npm i --save nest-commander @nestjs/common @nestjs/core`
3. `npm i --save-dev nest-commander-testing`

### Expected behavior

Should resolve dependency tree.

### Package

- [ ] <code>nest-commander</code>
- [ ] <code>nest-commander-schematics</code>
- [X] <code>nest-commander-testing</code>

### Package version

3.0.0

### Node.js version

16.13.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
Ah shoot, missed updating that peer dep. Thanks for pointing this out

**Comment by 123FLO321** [comment]
It should already be fixed with https://github.com/jmcdo29/nest-commander/commit/e78bd33c6721348a53104c92be1e14c9d2b32e25 but that is not included in the 3.0.0 tag

**Comment by jmcdo29** [comment]
Sure enough. I'll get a changeset for that in and released either today or tomorrow. You should be okay to ignore the warning for now

**Comment by jmcdo29** [comment]
Should be up with 3.0.1
