### ISSUE TITLE
Use less confusing examples in the docs

### ISSUE THREAD

**Issue by mikehaertl** [jmcdo29/nest-commander#574]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

The examples in the docs picked some unfavourable names for commands or questions/question sets.  As a newcomer this gave me some confusion for example here:

```typescript
@Command({
  name: 'run',
  arguments: '<task>',
  options: { isDefault: true }
})
export class TaskRunner extends CommandRunner {
  async run(
    inputs: string[],
    options: Record<string, any>
  ): Promise<void> {}
}
```

Is the `run` method related to the name of the command as used in `@Command()` above? I had to search for other examples to find out, that this is probably not the case.

Something similar happend in the inquirer example:

```typescript
@QuestionSet({ name: 'task' })
export class TaskQuestions {
  @Question({
    message: 'What task would you like to execute?',
    name: 'task'
  })
  parseTask(val: string) {
    return val;
  }
}
```

Both the set and the question use the name `task` here. Does it always have to be the same? If not, then this part of the command is confusing:

```typescript
task = (
        await this.inquirer.ask<{ task: string }>('task', undefined)
).task;
```

Now which `task` is this relating to? Is the `'task'` string argument relating to the question set or the question? And what about the property?

### Describe the solution you'd like

Use unambiguous names for commands, questions, etc. in examples that don't match any built in method or option names. Also don't use the same names for things that are not the same (i.e. Question set -> question) to make this more clear.

### What is the motivation / use case for changing the behavior?

Make the learning process smoother. Newcomers already have to deal with some mental load while studying the concepts. Confusing examples add to that load and thus distract the learner from the actual topic.

**Comment by jmcdo29** [comment]
Do you think it would be clearer if we called the command `exec` instead of `run` and used the string `task-questions` instead of `task`? I tried to make sure that everything was written out well _along with_ the code, like this statement on the `@QuestionSet()` decorator

> Provide the decorator a name via the options as well, as this name will be used by the `InquirerService` to know which question set to ask

**Comment by mikehaertl** [comment]
> Do you think it would be clearer if we called the command exec instead of run and used the string task-questions instead of task? 

Yeah, much better. I could even imagine something corny as as `my-exec` to make it very obvious which parts are the developers choice and which not.

> I tried to make sure that everything was written out well along with the code

Well, if you read everything very carefully it may be clear. But there's quite some new information to digest so I probably missed that part.
