### ISSUE TITLE
Type 'SyncCommand' is missing the following properties from type 'CommandRunner': command, setCommand

### ISSUE THREAD

**Issue by itinance** [jmcdo29/nest-commander#578]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

After upgrading a nestJS-project using nest-commander, I get the following compiler errors:

> src/command/sync.command.ts:8:2 - error TS2345: Argument of type 'typeof SyncCommand' is not assignable to parameter of type 'Type<CommandRunner>'.
>   Type 'SyncCommand' is missing the following properties from type 'CommandRunner': command, setCommand
> 

**nest-commander:**
The previous version was: 2.5.0
Current version 3.1.0

### Minimum reproduction code

Can be tested best with basic example code provided by nestJS:

Documentation: [https://docs.nestjs.com/recipes/nest-commander](https://docs.nestjs.com/recipes/nest-commander)

```
import { Command, CommandRunner, Option } from 'nest-commander';
import { Logger } from "@nestjs/common";

interface BasicCommandOptions {
  string?: string;
  boolean?: boolean;
  number?: number;
}

@Command({ name: 'basic', description: 'A parameter parse' })
export class BasicCommand implements CommandRunner {
  private logger = new Logger(BasicCommand.name);

  constructor() {}

  async run(passedParam: string[], options?: BasicCommandOptions): Promise<void> {

    if (options?.boolean !== undefined && options?.boolean !== null) {
      this.runWithBoolean(passedParam, options.boolean);
    } else if (options?.number) {
      this.runWithNumber(passedParam, options.number);
    } else if (options?.string) {
      this.runWithString(passedParam, options.string);
    } else {
      this.runWithNone(passedParam);
    }
  }

  @Option({
    flags: '-n, --number [number]',
    description: 'A basic number parser',
  })
  parseNumber(val: string): number {
    console.log("test", val)
    return Number(val);
  }

  @Option({
    flags: '-s, --string [string]',
    description: 'A string return',
  })
  parseString(val: string): string {
    return val;
  }

  @Option({
    flags: '-b, --boolean [boolean]',
    description: 'A boolean parser',
  })
  parseBoolean(val: string): boolean {
    return JSON.parse(val);
  }

  runWithString(param: string[], option: string): void {
    this.logger.log({ param, string: option });
  }

  runWithNumber(param: string[], option: number): void {
    console.log("REUNWITH NUMBER", param, option);
    this.logger.log({ param, number: option });
  }

  runWithBoolean(param: string[], option: boolean): void {
    this.logger.log({ param, boolean: option });
  }

  runWithNone(param: string[]): void {
    this.logger.log({ param });
  }
}
```

### Expected behavior

that it compiles

### Package

- [X] <code>nest-commander</code>
- [ ] <code>nest-commander-schematics</code>
- [ ] <code>nest-commander-testing</code>

### Package version

3.1.0

### Node.js version

16.13.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

Version info taken from `yarn.lock`:

```nest-commander@^3.1.0:
  version "3.1.0"
  resolved "https://registry.yarnpkg.com/nest-commander/-/nest-commander-3.1.0.tgz#88fc7cf515c63c21da76786c3ef8435bff2e98fc"
  integrity sha512-JWMH63VZ84YpKDtNFd6ERR/1h001SHNkaeLKkdQADhTs63rH6RVW/4FHzaGmYYMaZU9EJvhugFCBJvzhQg5vFQ==
  dependencies:
    "@golevelup/nestjs-discovery" "3.0.0"
    commander "9.4.0"
    cosmiconfig "7.0.1"
    inquirer "8.2.4"

**Comment by itinance** [comment]
I found the root cause:

The problematic line is:

```
export class BasicCommand implements CommandRunner {
```

instead it must `extend` from CommandRunner.

```
export class BasicCommand extends CommandRunner {
```

The weird thing is that it has been working this way using `implements` for almost a year running 2.x version although it MUST extend instead.

**Comment by jmcdo29** [comment]
Weird, it's almost like there's a [documented changelog that mentions something like this](https://github.com/jmcdo29/nest-commander/blob/main/packages/nest-commander/CHANGELOG.md#300).

I do need to still update the recipe in Nest's docs it seems, so thank you for pointing that out :smile:. I'll get a PR up for that soon. The rest of the [docs](https://nest-commander.jaymcdoniel.dev) should be up to date

**Comment by jmcdo29** [comment]
Oh, right. I should probably just point the npm README to the [documentation site](https://nest-commander.jaymcdoniel.dev) so that I don't have to manage two sets of docs

**Comment by simplenotezy** [comment]
Makes sense!

Great progress on the package by the way, it's been a while since I've been here, but we use it heavily for many tasks @DoubbleDK - great to see "questions" have been implemented as well, making it even more interactive.
