### ISSUE TITLE
nest-commander-schematics does nothing when ran in a monorepo

### ISSUE THREAD

**Issue by sonic1981** [jmcdo29/nest-commander#701]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Running `nest g -c nest-commander-schematics command` I follow the instructions in my nestjs mono-repo:

```bash
? Which project would you like to generate to? excel-to-sql
? What is the command name? convertXLX
? Is this the default command? Yes
? What is the name of the related question set? (Leave blank for none) 
```

At the end a provider is added to my module, but that's it:

```typescript
import { Module } from '@nestjs/common';
// This doesn't exist
import { ConvertXlxCommand } from './convert-xlx/convert-xlx.command';

@Module({
  imports: [],
  controllers: [],
  providers: [ConvertXlxCommand],
})
export class ExcelToSqlModule {}
```

### Minimum reproduction code

Setup a [nestjs monorepo with an app](https://docs.nestjs.com/cli/monorepo)

Run the following:

- `nest g -c nest-commander-schematics command`

```bash
? Which project would you like to generate to? excel-to-sql
? What is the command name? convertXLX
? Is this the default command? Yes
? What is the name of the related question set? (Leave blank for none) 
```

### Expected behavior

A provider should of been created

### Package

- [ ] <code>nest-commander</code>
- [X] <code>nest-commander-schematics</code>
- [ ] <code>nest-commander-testing</code>

### Package version

^3.0.0

### Node.js version

v18.12.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
Oohh I have not looked into making the schematic work inside of a monorepo :thinking: probably should look into that soon, there's most likely an easy silent error happening

**Comment by YeomansIII** [comment]
Hi @jmcdo29 ! Just wanted to ping you since I am also running into this issue now and to see if you may have made any progress on this or if you needed some help.

**Comment by jmcdo29** [comment]
Ah, right, need to get back to this. If you want to give it a shot go for it

**Comment by rtuin** [comment]
Also ran into this, though not sure where to start debugging. Using Nx with command:

```
nx g nest-commander-schematics:command --project=some-app
```

**Comment by jasonmacdonald** [comment]
Plugins also do not work with an NX monorepo as it tries to look for the plugin RC file in the root directory and not the project directory.

**Comment by jmcdo29** [comment]
`cosmiconfig` (what `nest-commander` uses for reading the rc file) by default uses the `process.cwd()` when running the `explorer.search()`. I can add in another option to make that configurable, just be aware that this could effect your CLI if you ever published it as well. I realize this is more for a "dev nicety" kind of option, so I'll make sure to add that to the documentation, but just wanted to call attention to it

**Comment by claudecoder12** [comment]
Any updates?

**Comment by jmcdo29** [comment]
I believe that (finally) with 3.0.2 this should be fixed. Turns out when I moved over to the Nx monorepo, I missed a post-build step to move over the template files for the schematics, so it wasn't broken for _just_ monorepos, it wasn't creating files at all.

That should be resolved now.
