### ISSUE TITLE
There is no way to cleanly recover from an uncaught exception

### ISSUE THREAD

**Issue by david-catch** [jmcdo29/nest-commander#794]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When a CLI command involves a long-running task or some persistent connection, and then an unhandled exception is thrown, the Node process will not terminate and run perpetually.

An unhandled exception seem to cause the entire NestJS app to be abruptly halted without a chance to do a clean up. I believe this is because when an unhandled exception is thrown, the `runApplication` function doesn't catch the exception and never returns with the app instance. Therefore the caller also never got a chance to call `app.close()` to properly shut down the application where clean up takes place.

### Minimum reproduction code

The situation is reproduced in this repository: https://github.com/david-catch/nest-commander-exception-bug

### Expected behavior

When a CLI command involving a long-running job or persistent connection faces an unhandled exception, the `app.close()` should still be closed to allow the app to properly clean up the resources and allowing the Node process to exit instead of getting stuck.

### Package

- [X] <code>nest-commander</code>
- [ ] <code>nest-commander-schematics</code>
- [ ] <code>nest-commander-testing</code>

### Package version

3.5.0

### Node.js version

16.13.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
Looks like I can add a `try/catch` around the `this.command.parseAsync` in the `CommandRunnerService` (what actually executes the command) to handle this. I'll probably need to add another option to the `CommandFactory` for how to handle these errors and by default just `process.stderr.write(err.toString())` or similar. I've got a few additions coming down the pipe for this package so I'll bundle them all together under 3.6.0 probably

**Comment by jmcdo29** [comment]
[Published in 3.6.0](https://nest-commander.jaymcdoniel.dev/en/api/#commandfactory)

**Comment by david-catch** [comment]
Thanks for pushing the update @jmcdo29! One thing I noticed is that the new `serviceErrorHandler` option is not being parsed by the function `CommandFactory.getOptions()`, which means it is ignored and doesn't override the default handler. I believe updating that one function should fix it!

(PS: I've updated the simple reproduction repo with the new version 3.6.0 to illustrate the issue)

**Comment by jmcdo29** [comment]
Oh shoot! Nice catch. Mind paying that in a PR and adding a patch changeset using `pnpm changeset`?

**Comment by david-catch** [comment]
I don't mind doing that, just that I'm not familiar with using `pnpm changeset`. I'll give it a shot regardless :)

**Comment by david-catch** [comment]
I've created a PR here https://github.com/jmcdo29/nest-commander/pull/807
