### ISSUE TITLE
MODULE_NOT_FOUND , script don't see src

### ISSUE THREAD

**Issue by pogran** [jmcdo29/nest-commander#797]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

when I start my command like this

ts-node src/main.ts genre ,

i have error MODULE_NOT_FOUND for my services which I import with path started from src

### Minimum reproduction code

import { Command, CommandRunner, Option } from 'nest-commander';
import { PrismaService } from 'src/services/prisma.service';

@Command({
	name: 'genre',
	options: { isDefault: true },
})
export class GenreRunner extends CommandRunner {
	constructor(
		// private readonly prismaOldService: PrismaOldService,
		private readonly prismaService: PrismaService
	) {
		super();
	}

	async run(inputs: string[], options: Record<string, any>): Promise<void> {
		console.log('int', inputs);
		console.log('options', options);
	}
	@Option({
		flags: '-s, --shell <shell>',
		description: 'A different shell to spawn than the default',
	})
	parseShell(val: string) {
		console.log('val', val);
		return val;
	}

	@Option({
		flags: '-n, --number <number>',
		description: 'Numbers different',
	})
	parseS(val: string) {
		return Number(val);
	}
}

### Expected behavior

result will be in function run

### Package

- [X] <code>nest-commander</code>
- [ ] <code>nest-commander-schematics</code>
- [ ] <code>nest-commander-testing</code>

### Package version

3.5.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
That's an issue with your configuration and `ts-node`, not a problem with the library. I believe it has to do with the `tsconfig` option `baseUrl`. If you get me a cloneable repo I can get you a better answer

**Comment by pogran** [comment]
thx, i have found solution :)
