### ISSUE TITLE
Module '"inquirer"' has no exported member 'Inquirer'

### ISSUE THREAD

**Issue by amine0909** [jmcdo29/nest-commander#834]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have an old nestjs project and I had to migrate and upgrade the nest-commander version to the latest, but I got this error when running the application

### Minimum reproduction code

![image](https://user-images.githubusercontent.com/27707941/225153605-f5d35d65-f7ad-48b2-845a-277a4219d328.png)

### Expected behavior

Should run without errors

### Package

- [X] <code>nest-commander</code>
- [ ] <code>nest-commander-schematics</code>
- [ ] <code>nest-commander-testing</code>

### Package version

3.6.1

### Node.js version

18

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by amine0909** [comment]
@jmcdo29 

```ts
// user.command.ts

import { Command, CommandRunner, InquirerService } from 'nest-commander';
import { UserOptions } from './user.interface';
import { UsersService } from '../users.service';

@Command({
  name: 'create:admin',
})
export class UserCreate extends CommandRunner {
  constructor(
    private readonly inquirer: InquirerService,
    private readonly userService: UsersService,
  ) {
    super();
  }
  async run(inputs: string[], options: UserOptions): Promise<void> {
    const { username, password, email } = await this.inquirer.prompt(
      'userInformation',
      options,
    );
    // Create the user
    try {
      console.log('Start Creating User ... ');
      await this.userService.create({
        username,
        password,
        email,
      });
      console.log('Account has been creating successfully');
    } catch (error) {
      console.error('There is a problem');
      console.error(error.detail);
    } finally {
      console.info('Waiting to close the app process...');
    }
  }
}
```

For info, i got that error when i execute "npm run start:dev" to run launch the nestjs project

**Comment by jmcdo29** [comment]
A minimum reproduction would be a git repo I could clone, install, and view the error with

**Comment by amine0909** [comment]
> A minimum reproduction would be a git repo I could clone, install, and view the error with

Sorry, i think i can't .
It's the company's project, i can't expose the whole repo

**Comment by jmcdo29** [comment]
For a minimum reproduction, it should not be tied to any business logic, it should be **minimum** to show the error.

I'll try to create something locally, but there's no guarantees that what I make will reproduce your error

**Comment by jmcdo29** [comment]
In the most basic minimum setup, I cannot repeat this error, so I will need some sort of minimum reproduction from you to get this same error so I can determine what's happening

**Comment by amine0909** [comment]
@jmcdo29 Hello again, sorry for the late reply but i fixed it, it was my nestjs version
The problem was shown when i updated the @nestjs/common and @nestjs/core to 9.3.9 , so i had to downgrade to version 9.0.0

**Comment by amine0909** [comment]
but thank you very much for helping me :)
