### ISSUE TITLE
Feature request to generate shell auto completion

### ISSUE THREAD

**Issue by yusuftaufiq** [jmcdo29/nest-commander#849]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I thought it would be cool if by default Nest Commander could generate tab auto-completion for some shells like bash, zsh, fish, and powershell.

### Describe the solution you'd like

The solution I imagined is something like Nest Commander provides an option to enable the auto-completion feature when invoking `CommandFactory.run(...)`. And when it is enabled, automatically command like the `completion <shell>` is available, which can be used like the `app completion bash` to generate shell script output for adding an auto-completion feature according to the selected shell.

### What is the motivation / use case for changing the behavior?

Since most modern shells support tab auto-completion, so I think this feature can improve the user experience when using apps built with Nest Commander.

**Comment by tukusejssirs** [comment]
I am interested in this feature as well. It could be behind a global config (passed to `CommandFactory#run` et al).

**Comment by Avivbens** [comment]
Sounds lovely 👍 

Looking for this one
Does somebody wants to take this into a PR with me?

**Comment by jmcdo29** [comment]
Pull Requests are more than welcome! I haven't had the time to look into how to start generating this between work and family

**Comment by Avivbens** [comment]
I'll try to tackle that 👍

**Comment by Avivbens** [comment]
Here is a PR:
https://github.com/jmcdo29/nest-commander/pull/1045

DEMO video:

https://github.com/jmcdo29/nest-commander/assets/77183871/177d3f68-f8ba-4e9a-9574-744ce09f093a

**Comment by tukusejssirs** [comment]
I haven’t tested it out, but it looks awesome! Thanks, @Avivbens! :pray:

**Comment by jmcdo29** [comment]
This is released as a part of 3.12.0 :tada:
