### ISSUE TITLE
Issue with inquirer import when already used in project

### ISSUE THREAD

**Issue by floriantz** [jmcdo29/nest-commander#851]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

There's a closed issue for this, but it is closed, and I have a minimum reproduction repository. This happens in one of our projects where I'm trying to add `nest-commander`, I've tried using versions that match the version used in our project but no luck so far I don't understand the issue 🤔 

```
> nest build

node_modules/nest-commander/src/inquirer.service.d.ts:2:19 - error TS2305: Module '"inquirer"' has no exported member 'Inquirer'.

2 import { Answers, Inquirer as InquirerType } from 'inquirer';
                    ~~~~~~~~
node_modules/nest-commander/src/inquirer.service.d.ts:2:19 - error TS2305: Module '"inquirer"' has no exported member 'Inquirer'.

2 import { Answers, Inquirer as InquirerType } from 'inquirer';
                    ~~~~~~~~

Found 2 error(s).
``` 

### Minimum reproduction code

https://github.com/floriantz/repro-nest-commander

### Expected behavior

Should be able to build this project.

### Package

- [X] <code>nest-commander</code>
- [ ] <code>nest-commander-schematics</code>
- [ ] <code>nest-commander-testing</code>

### Package version

3.6.1

### Node.js version

16.14.2

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [X] Linux

**Comment by jmcdo29** [comment]
Ah, it looks like the `@types/` for inquirer took away the `Inquirer` type after `8.2.1` which is what this uses to build. I'll see what it should be replaced with so that it keeps working as intended

**Comment by floriantz** [comment]
> Ah, it looks like the @types/ for inquirer took away the Inquirer type after 8.2.1 which is what this uses to build. I'll see what it should be replaced with so that it keeps working as intended

Ah indeed ! I'll see if I can bring the inquirer versions + the types down in my project for now, but thanks for having a look at the issue I did miss the root cause 👍 

Hope the reproduction was easy to work with.
