### ISSUE TITLE
Change CommandFactory in order to be able to access the `INestApplicationContext` before runner execution.

### ISSUE THREAD

**Issue by floriantz** [jmcdo29/nest-commander#852]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Hello ! First of all thank you for this very nice project !

In the nestjs application I have and on which I'd like to add a cli, we are relying on [nestjs-pino](https://github.com/iamolegga/nestjs-pino) with a custom `LoggerModule` which we register like so:

```typescript
const app = await NestFactory.create(AppModule, { bufferLogs: true });
app.useLogger(app.get(Logger));
```

As the `CommandFactory` is currently designed, it is impossible to access the `INestApplicationContext` returned from the `NestFactory.create(...)` before the runner is run, which is what I'd like to have control on.

### Describe the solution you'd like

I understand the benefits of having most `CommandFactory` methods as `private` but eventually making those `protected` or changing the API might allow extending the `CommandFactory` and make a custom one that fits more complex use-cases where accessing instantiated modules before we start the command runner is necessary.

### What is the motivation / use case for changing the behavior?

The current API is a bit too restrictive and block our usage of `nestjs-pino` in our current app. A bit more flexibility on the `CommandFactory` would unblock some usages such as this one.

**Comment by jmcdo29** [comment]
I'm fine with a PR to make most of the methods `protected` instead to give that flexibility. I don't think a logger makes much sense in the final version of the CLI, at least for the Nest startup logs, but that's my opinion

**Comment by jmcdo29** [comment]
I'll get to work on this here soon to add in some more usability for if you need scenarios like your use case :)

**Comment by grant-otus** [comment]
I'd like to +1 this functionality, I'm also trying to implement pino logger into a CLI to get more details on some of the inner working.

**Comment by jmcdo29** [comment]
@grant-otus check out the linked PR and see if you believe it should fit your use case :)

**Comment by grant-otus** [comment]
@jmcdo29 I believe it will, all I need is access to the INestApplicationContext, so that looks golden to me.

**Comment by jmcdo29** [comment]
Available in 3.7.0

**Comment by Sadzurami** [comment]
Hello!
Thanks for great project and for changes made here. Now app creation looks much better.
But, can we pass to options all available options of NestFactory.createApplicationContext? 

As mentioned above, i would like to logs all with nestjs-pino, but initial logs are missed since 'bufferLogs' are not set here
https://github.com/jmcdo29/nest-commander/blob/d3d89b403bbd5b969f39acc0b182d0241df31e80/packages/nest-commander/src/command.factory.ts#L49C10-L54

Maybe merge CommandFactoryRunOptions with Partial<NestApplicationContextOptions>?
https://github.com/jmcdo29/nest-commander/blob/d3d89b403bbd5b969f39acc0b182d0241df31e80/packages/nest-commander/src/command-factory.interface.ts#LL12C1-L20C2

Also.. I think this is bug. If we pass empty object to CommandFactory.createWithoutRunning options or for example 'cliName' - as result built-in nest logger will be enabled.

**Comment by jmcdo29** [comment]
> Also.. I think this is a bug. If we pass an empty object in the CommandFactory.createWithoutRunning option or for example 'cliName' - as a result, the built-in Nest logger will be enabled (but we did not enable it ourselves).

Do you think you could make a reproduction with this? Just want to double check it/make it easily added to the test suite

> As mentioned above, i would like to logs all with nestjs-pino, but initial logs are missed since 'bufferLogs' are not set here.
>
> [d3d89b4/packages/nest-commander/src/command.factory.ts#L49C10-L54](https://github.com/jmcdo29/nest-commander/blob/d3d89b403bbd5b969f39acc0b182d0241df31e80/packages/nest-commander/src/command.factory.ts#L49C10-L54)
>
> Maybe merge CommandFactoryRunOptions with Partial<NestApplicationContextOptions> ?
>
> [d3d89b4/packages/nest-commander/src/command-factory.interface.ts#LL12C1-L20C2](https://github.com/jmcdo29/nest-commander/blob/d3d89b403bbd5b969f39acc0b182d0241df31e80/packages/nest-commander/src/command-factory.interface.ts#LL12C1-L20C2)

Makes sense.  We should be able to merge those interfaces pretty easily. 

> What do you think about my previous message?

All sounds good. @Sadzurami Would you like to work on a PR for this? Apologies for the slight delay, I was taking the weekend to enjoy some time with family :)

**Comment by Sadzurami** [comment]
@jmcdo29 Sorry to bother you, I didn't notice it was the weekend.

PR created.

**Comment by jmcdo29** [comment]
Available in 3.8.0

**Comment by coler-j** [comment]
@Sadzurami do you have an example of how you pass your pino logger?

**Comment by coler-j** [comment]
NVM It is

```
export async function bootstrap() {
  const app = await CommandFactory.createWithoutRunning(
    AppModule,
    standaloneAppConfigurationOptions,
  );
  app.useLogger(.... ) < do what need to do
  await CommandFactory.runApplication(app);
}

void bootstrap();
```
