### ISSUE TITLE
There is a dependency conflict between the @types/inquirer package and the nest-commander package

### ISSUE THREAD

**Issue by todbapi** [jmcdo29/nest-commander#950]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Versions

>= 3.7.1

### Describe the regression

# npm resolution error report

While resolving: tuition-backend@0.0.1
Found: @types/inquirer@9.0.3
node_modules/@types/inquirer
  dev @types/inquirer@"^9.0.3" from the root project

Could not resolve dependency:
peer @types/inquirer@"^8.1.3" from nest-commander@3.8.0
node_modules/nest-commander
  nest-commander@"^3.7.1" from the root project

Fix the upstream dependency conflict, or retry
this command with --force or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

### Minimum reproduction code

```ts

```

### Expected behavior

npm package installation without dependency conflict.

**Comment by jmcdo29** [comment]
Nest commander exchange inquirer version 8 and the types to match. V9 is an ESM module that is not fully supported yet, hence the specified version in the peer dependencies

**Comment by todbapi** [comment]
So @types/inquirer 8.1.3 is working fine. So Closing this.
